#!/usr/bin/env python3
"""LWEP protobuf tester — CLIENT (Python).

Builds the four canonical messages (values from ../../messages/), sends each as a
framed message, receives the server's echo, and asserts field-by-field
round-trip equality. Exit code 0 on success, 1 on any mismatch.

Usage:  python client.py [host] [port]     (default 127.0.0.1 9001)
"""
import os
import socket
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
try:
    import lwep_pb2  # generated by generate.ps1 (git-ignored)
except ImportError:
    sys.exit("lwep_pb2 not found — run generate.ps1 first (see README).")

T_SENSOR, T_WAVEFORM, T_STATUS, T_TELEMETRY = 1, 2, 3, 4


def recv_exact(sock, n):
    buf = b""
    while len(buf) < n:
        chunk = sock.recv(n - len(buf))
        if not chunk:
            return None
        buf += chunk
    return buf


def recv_frame(sock):
    hdr = recv_exact(sock, 5)
    if hdr is None:
        return None
    length, msg_type = struct.unpack(">IB", hdr)
    payload = recv_exact(sock, length) if length else b""
    return msg_type, payload


def send_frame(sock, msg_type, payload):
    sock.sendall(struct.pack(">IB", len(payload), msg_type) + payload)


# ---- canonical builders (values mirror ../../messages/) ------------------
def make_sensor(pb=lwep_pb2):
    m = pb.SensorReading()
    m.id = 4097
    m.sensor_type = pb.TEMPERATURE
    m.value = 23.5
    m.value_precise = 23.481523
    m.timestamp = 1720224000000
    m.is_valid = True
    m.raw_count = -12345
    m.label = "cabin-temp"
    return m


def make_waveform(pb=lwep_pb2):
    m = pb.Waveform()
    m.channel = 3
    m.samples.extend([0, 100, -100, 32767, -32768, 5, 6, 7, 8, 9])
    m.gains.extend([1.0, 0.5, 0.25, 2.0])
    m.tags.extend(["ch3", "raw", "v2"])
    m.checksum = 0xDEADBEEF
    return m


def make_status(pb=lwep_pb2):
    m = pb.DeviceStatus()
    m.device_id = 0x2A2A
    m.flags = (1 << 0) | (1 << 2) | (6 << 4) | (87 << 8)  # 0x5765
    m.error_code = 0
    return m


def make_telemetry(pb=lwep_pb2):
    m = pb.TelemetryPacket()
    m.header.version = 2
    m.header.seq = 42
    m.header.source_addr = 0x00A5
    m.reading.CopyFrom(make_sensor(pb))
    m.waveform.CopyFrom(make_waveform(pb))
    m.status.CopyFrom(make_status(pb))
    e0 = m.extra_readings.add()
    e0.id, e0.sensor_type, e0.value, e0.value_precise = 1, pb.PRESSURE, 101.3, 101.325
    e0.timestamp, e0.is_valid, e0.raw_count, e0.label = 1720224000001, True, 2048, "baro"
    e1 = m.extra_readings.add()
    e1.id, e1.sensor_type, e1.value, e1.value_precise = 2, pb.HUMIDITY, 45.0, 45.0
    e1.timestamp, e1.is_valid, e1.raw_count, e1.label = 1720224000002, False, 0, "rh"
    m.payload = bytes([0x01, 0x02, 0x03, 0x04, 0xFF, 0xFE, 0xFD, 0x00])
    return m


def roundtrip(sock, name, msg_type, msg):
    send_frame(sock, msg_type, msg.SerializeToString())
    rtype, payload = recv_frame(sock)
    echo = type(msg)()
    echo.ParseFromString(payload)
    ok = (rtype == msg_type) and (echo == msg)
    print(f"[client] {name:16s} {'PASS' if ok else 'FAIL'}")
    if not ok:
        print("  sent:", str(msg).replace("\n", " "))
        print("  got :", str(echo).replace("\n", " "))
    return ok


def main():
    host = sys.argv[1] if len(sys.argv) > 1 else "127.0.0.1"
    port = int(sys.argv[2]) if len(sys.argv) > 2 else 9001
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.connect((host, port))
    print(f"[client] connected to {host}:{port}")
    all_ok = True
    with sock:
        all_ok &= roundtrip(sock, "SensorReading", T_SENSOR, make_sensor())
        all_ok &= roundtrip(sock, "Waveform", T_WAVEFORM, make_waveform())
        all_ok &= roundtrip(sock, "DeviceStatus", T_STATUS, make_status())
        all_ok &= roundtrip(sock, "TelemetryPacket", T_TELEMETRY, make_telemetry())
    print(f"[client] {'ALL PASS' if all_ok else 'FAILURES PRESENT'}")
    sys.exit(0 if all_ok else 1)


if __name__ == "__main__":
    main()
