#!/usr/bin/env python3
"""LWEP protobuf tester — SERVER (Python).

Listens on a TCP port, decodes each framed message, prints a field dump, and
echoes the message back re-encoded. Talks to either the Python client or the
C++ (nanopb) client — they all share the wire framing in ../../common/framing.md.

Usage:  python server.py [port]     (default port 9001)
"""
import os
import socket
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
try:
    import lwep_pb2  # generated by generate.ps1 (git-ignored)
except ImportError:
    sys.exit("lwep_pb2 not found — run generate.ps1 first (see README).")

# msg_type ids (see ../../common/framing.md)
T_SENSOR, T_WAVEFORM, T_STATUS, T_TELEMETRY = 1, 2, 3, 4


def recv_exact(sock, n):
    buf = b""
    while len(buf) < n:
        chunk = sock.recv(n - len(buf))
        if not chunk:
            return None
        buf += chunk
    return buf


def recv_frame(sock):
    hdr = recv_exact(sock, 5)
    if hdr is None:
        return None
    length, msg_type = struct.unpack(">IB", hdr)
    payload = recv_exact(sock, length) if length else b""
    if payload is None:
        return None
    return msg_type, payload


def send_frame(sock, msg_type, payload):
    sock.sendall(struct.pack(">IB", len(payload), msg_type) + payload)


def dump(msg_type, msg):
    names = {1: "SensorReading", 2: "Waveform", 3: "DeviceStatus", 4: "TelemetryPacket"}
    print(f"[server] recv type={msg_type} ({names.get(msg_type, '?')})")
    print("         " + str(msg).replace("\n", "\n         ").rstrip())


def decode(msg_type, payload):
    cls = {
        T_SENSOR: lwep_pb2.SensorReading,
        T_WAVEFORM: lwep_pb2.Waveform,
        T_STATUS: lwep_pb2.DeviceStatus,
        T_TELEMETRY: lwep_pb2.TelemetryPacket,
    }[msg_type]
    msg = cls()
    msg.ParseFromString(payload)
    return msg


def main():
    port = int(sys.argv[1]) if len(sys.argv) > 1 else 9001
    srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    srv.bind(("0.0.0.0", port))
    srv.listen(1)
    print(f"[server] listening on :{port}")
    conn, addr = srv.accept()
    print(f"[server] client connected from {addr}")
    with conn:
        count = 0
        while True:
            frame = recv_frame(conn)
            if frame is None:
                break
            msg_type, payload = frame
            msg = decode(msg_type, payload)
            dump(msg_type, msg)
            send_frame(conn, msg_type, msg.SerializeToString())  # echo
            count += 1
    print(f"[server] done, echoed {count} message(s)")


if __name__ == "__main__":
    main()
